/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CostsRouteImport } from './routes/costs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as ChecklistIndexRouteImport } from './routes/checklist.index'
import { Route as SalesStatsRouteImport } from './routes/sales.stats'
import { Route as SalesSettingsRouteImport } from './routes/sales.settings'
import { Route as InventoryItemIdRouteImport } from './routes/inventory.$itemId'
import { Route as EventsSeriesRouteImport } from './routes/events.series'
import { Route as EventsScheduleRouteImport } from './routes/events.schedule'
import { Route as EventsHistoryRouteImport } from './routes/events.history'
import { Route as ChecklistSessionIdRouteImport } from './routes/checklist.$sessionId'
import { Route as SalesSessionIdIndexRouteImport } from './routes/sales.$sessionId.index'
import { Route as SalesSessionIdReportRouteImport } from './routes/sales.$sessionId.report'
import { Route as EventsInstanceInstanceIdRouteImport } from './routes/events.instance.$instanceId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsRoute = CostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const ChecklistIndexRoute = ChecklistIndexRouteImport.update({
  id: '/checklist/',
  path: '/checklist/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesStatsRoute = SalesStatsRouteImport.update({
  id: '/sales/stats',
  path: '/sales/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesSettingsRoute = SalesSettingsRouteImport.update({
  id: '/sales/settings',
  path: '/sales/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryItemIdRoute = InventoryItemIdRouteImport.update({
  id: '/inventory/$itemId',
  path: '/inventory/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSeriesRoute = EventsSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => EventsRoute,
} as any)
const EventsScheduleRoute = EventsScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => EventsRoute,
} as any)
const EventsHistoryRoute = EventsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => EventsRoute,
} as any)
const ChecklistSessionIdRoute = ChecklistSessionIdRouteImport.update({
  id: '/checklist/$sessionId',
  path: '/checklist/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesSessionIdIndexRoute = SalesSessionIdIndexRouteImport.update({
  id: '/sales/$sessionId/',
  path: '/sales/$sessionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesSessionIdReportRoute = SalesSessionIdReportRouteImport.update({
  id: '/sales/$sessionId/report',
  path: '/sales/$sessionId/report',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsInstanceInstanceIdRoute =
  EventsInstanceInstanceIdRouteImport.update({
    id: '/instance/$instanceId',
    path: '/instance/$instanceId',
    getParentRoute: () => EventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/costs': typeof CostsRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/checklist/$sessionId': typeof ChecklistSessionIdRoute
  '/events/history': typeof EventsHistoryRoute
  '/events/schedule': typeof EventsScheduleRoute
  '/events/series': typeof EventsSeriesRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/sales/settings': typeof SalesSettingsRoute
  '/sales/stats': typeof SalesStatsRoute
  '/checklist/': typeof ChecklistIndexRoute
  '/events/': typeof EventsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/events/instance/$instanceId': typeof EventsInstanceInstanceIdRoute
  '/sales/$sessionId/report': typeof SalesSessionIdReportRoute
  '/sales/$sessionId/': typeof SalesSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/costs': typeof CostsRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/checklist/$sessionId': typeof ChecklistSessionIdRoute
  '/events/history': typeof EventsHistoryRoute
  '/events/schedule': typeof EventsScheduleRoute
  '/events/series': typeof EventsSeriesRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/sales/settings': typeof SalesSettingsRoute
  '/sales/stats': typeof SalesStatsRoute
  '/checklist': typeof ChecklistIndexRoute
  '/events': typeof EventsIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/sales': typeof SalesIndexRoute
  '/events/instance/$instanceId': typeof EventsInstanceInstanceIdRoute
  '/sales/$sessionId/report': typeof SalesSessionIdReportRoute
  '/sales/$sessionId': typeof SalesSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/costs': typeof CostsRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/checklist/$sessionId': typeof ChecklistSessionIdRoute
  '/events/history': typeof EventsHistoryRoute
  '/events/schedule': typeof EventsScheduleRoute
  '/events/series': typeof EventsSeriesRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/sales/settings': typeof SalesSettingsRoute
  '/sales/stats': typeof SalesStatsRoute
  '/checklist/': typeof ChecklistIndexRoute
  '/events/': typeof EventsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/events/instance/$instanceId': typeof EventsInstanceInstanceIdRoute
  '/sales/$sessionId/report': typeof SalesSessionIdReportRoute
  '/sales/$sessionId/': typeof SalesSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/costs'
    | '/events'
    | '/login'
    | '/meetings'
    | '/settings'
    | '/checklist/$sessionId'
    | '/events/history'
    | '/events/schedule'
    | '/events/series'
    | '/inventory/$itemId'
    | '/sales/settings'
    | '/sales/stats'
    | '/checklist/'
    | '/events/'
    | '/inventory/'
    | '/sales/'
    | '/events/instance/$instanceId'
    | '/sales/$sessionId/report'
    | '/sales/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/costs'
    | '/login'
    | '/meetings'
    | '/settings'
    | '/checklist/$sessionId'
    | '/events/history'
    | '/events/schedule'
    | '/events/series'
    | '/inventory/$itemId'
    | '/sales/settings'
    | '/sales/stats'
    | '/checklist'
    | '/events'
    | '/inventory'
    | '/sales'
    | '/events/instance/$instanceId'
    | '/sales/$sessionId/report'
    | '/sales/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/costs'
    | '/events'
    | '/login'
    | '/meetings'
    | '/settings'
    | '/checklist/$sessionId'
    | '/events/history'
    | '/events/schedule'
    | '/events/series'
    | '/inventory/$itemId'
    | '/sales/settings'
    | '/sales/stats'
    | '/checklist/'
    | '/events/'
    | '/inventory/'
    | '/sales/'
    | '/events/instance/$instanceId'
    | '/sales/$sessionId/report'
    | '/sales/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CostsRoute: typeof CostsRoute
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRoute
  SettingsRoute: typeof SettingsRoute
  ChecklistSessionIdRoute: typeof ChecklistSessionIdRoute
  InventoryItemIdRoute: typeof InventoryItemIdRoute
  SalesSettingsRoute: typeof SalesSettingsRoute
  SalesStatsRoute: typeof SalesStatsRoute
  ChecklistIndexRoute: typeof ChecklistIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  SalesSessionIdReportRoute: typeof SalesSessionIdReportRoute
  SalesSessionIdIndexRoute: typeof SalesSessionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs': {
      id: '/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof CostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/checklist/': {
      id: '/checklist/'
      path: '/checklist'
      fullPath: '/checklist/'
      preLoaderRoute: typeof ChecklistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/stats': {
      id: '/sales/stats'
      path: '/sales/stats'
      fullPath: '/sales/stats'
      preLoaderRoute: typeof SalesStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/settings': {
      id: '/sales/settings'
      path: '/sales/settings'
      fullPath: '/sales/settings'
      preLoaderRoute: typeof SalesSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$itemId': {
      id: '/inventory/$itemId'
      path: '/inventory/$itemId'
      fullPath: '/inventory/$itemId'
      preLoaderRoute: typeof InventoryItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/series': {
      id: '/events/series'
      path: '/series'
      fullPath: '/events/series'
      preLoaderRoute: typeof EventsSeriesRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/schedule': {
      id: '/events/schedule'
      path: '/schedule'
      fullPath: '/events/schedule'
      preLoaderRoute: typeof EventsScheduleRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/history': {
      id: '/events/history'
      path: '/history'
      fullPath: '/events/history'
      preLoaderRoute: typeof EventsHistoryRouteImport
      parentRoute: typeof EventsRoute
    }
    '/checklist/$sessionId': {
      id: '/checklist/$sessionId'
      path: '/checklist/$sessionId'
      fullPath: '/checklist/$sessionId'
      preLoaderRoute: typeof ChecklistSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/$sessionId/': {
      id: '/sales/$sessionId/'
      path: '/sales/$sessionId'
      fullPath: '/sales/$sessionId/'
      preLoaderRoute: typeof SalesSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/$sessionId/report': {
      id: '/sales/$sessionId/report'
      path: '/sales/$sessionId/report'
      fullPath: '/sales/$sessionId/report'
      preLoaderRoute: typeof SalesSessionIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/instance/$instanceId': {
      id: '/events/instance/$instanceId'
      path: '/instance/$instanceId'
      fullPath: '/events/instance/$instanceId'
      preLoaderRoute: typeof EventsInstanceInstanceIdRouteImport
      parentRoute: typeof EventsRoute
    }
  }
}

interface EventsRouteChildren {
  EventsHistoryRoute: typeof EventsHistoryRoute
  EventsScheduleRoute: typeof EventsScheduleRoute
  EventsSeriesRoute: typeof EventsSeriesRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsInstanceInstanceIdRoute: typeof EventsInstanceInstanceIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsHistoryRoute: EventsHistoryRoute,
  EventsScheduleRoute: EventsScheduleRoute,
  EventsSeriesRoute: EventsSeriesRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsInstanceInstanceIdRoute: EventsInstanceInstanceIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CostsRoute: CostsRoute,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRoute,
  SettingsRoute: SettingsRoute,
  ChecklistSessionIdRoute: ChecklistSessionIdRoute,
  InventoryItemIdRoute: InventoryItemIdRoute,
  SalesSettingsRoute: SalesSettingsRoute,
  SalesStatsRoute: SalesStatsRoute,
  ChecklistIndexRoute: ChecklistIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  SalesSessionIdReportRoute: SalesSessionIdReportRoute,
  SalesSessionIdIndexRoute: SalesSessionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
