/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as CostsIndexRouteImport } from './routes/costs.index'
import { Route as ChecklistIndexRouteImport } from './routes/checklist.index'
import { Route as SalesStatsRouteImport } from './routes/sales.stats'
import { Route as SalesSettingsRouteImport } from './routes/sales.settings'
import { Route as InventoryNewRouteImport } from './routes/inventory.new'
import { Route as InventoryListRouteImport } from './routes/inventory.list'
import { Route as InventoryItemIdRouteImport } from './routes/inventory.$itemId'
import { Route as EventsSeriesRouteImport } from './routes/events.series'
import { Route as EventsScheduleRouteImport } from './routes/events.schedule'
import { Route as EventsHistoryRouteImport } from './routes/events.history'
import { Route as ChecklistSettingsRouteImport } from './routes/checklist.settings'
import { Route as ChecklistSessionIdRouteImport } from './routes/checklist.$sessionId'
import { Route as SalesSessionIdIndexRouteImport } from './routes/sales.$sessionId.index'
import { Route as CostsProductsIndexRouteImport } from './routes/costs.products.index'
import { Route as SalesSessionIdReportRouteImport } from './routes/sales.$sessionId.report'
import { Route as InventoryLogRestockRouteImport } from './routes/inventory.log.restock'
import { Route as InventoryLogEventRouteImport } from './routes/inventory.log.event'
import { Route as InventoryLogBatchRouteImport } from './routes/inventory.log.batch'
import { Route as EventsInstanceInstanceIdRouteImport } from './routes/events.instance.$instanceId'
import { Route as CostsProductsIdRouteImport } from './routes/costs.products.$id'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const CostsIndexRoute = CostsIndexRouteImport.update({
  id: '/costs/',
  path: '/costs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistIndexRoute = ChecklistIndexRouteImport.update({
  id: '/checklist/',
  path: '/checklist/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesStatsRoute = SalesStatsRouteImport.update({
  id: '/sales/stats',
  path: '/sales/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesSettingsRoute = SalesSettingsRouteImport.update({
  id: '/sales/settings',
  path: '/sales/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryNewRoute = InventoryNewRouteImport.update({
  id: '/inventory/new',
  path: '/inventory/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryListRoute = InventoryListRouteImport.update({
  id: '/inventory/list',
  path: '/inventory/list',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryItemIdRoute = InventoryItemIdRouteImport.update({
  id: '/inventory/$itemId',
  path: '/inventory/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSeriesRoute = EventsSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => EventsRoute,
} as any)
const EventsScheduleRoute = EventsScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => EventsRoute,
} as any)
const EventsHistoryRoute = EventsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => EventsRoute,
} as any)
const ChecklistSettingsRoute = ChecklistSettingsRouteImport.update({
  id: '/checklist/settings',
  path: '/checklist/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistSessionIdRoute = ChecklistSessionIdRouteImport.update({
  id: '/checklist/$sessionId',
  path: '/checklist/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesSessionIdIndexRoute = SalesSessionIdIndexRouteImport.update({
  id: '/sales/$sessionId/',
  path: '/sales/$sessionId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CostsProductsIndexRoute = CostsProductsIndexRouteImport.update({
  id: '/costs/products/',
  path: '/costs/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesSessionIdReportRoute = SalesSessionIdReportRouteImport.update({
  id: '/sales/$sessionId/report',
  path: '/sales/$sessionId/report',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryLogRestockRoute = InventoryLogRestockRouteImport.update({
  id: '/inventory/log/restock',
  path: '/inventory/log/restock',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryLogEventRoute = InventoryLogEventRouteImport.update({
  id: '/inventory/log/event',
  path: '/inventory/log/event',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryLogBatchRoute = InventoryLogBatchRouteImport.update({
  id: '/inventory/log/batch',
  path: '/inventory/log/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsInstanceInstanceIdRoute =
  EventsInstanceInstanceIdRouteImport.update({
    id: '/instance/$instanceId',
    path: '/instance/$instanceId',
    getParentRoute: () => EventsRoute,
  } as any)
const CostsProductsIdRoute = CostsProductsIdRouteImport.update({
  id: '/costs/products/$id',
  path: '/costs/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/simulate': typeof SimulateRoute
  '/tasks': typeof TasksRoute
  '/checklist/$sessionId': typeof ChecklistSessionIdRoute
  '/checklist/settings': typeof ChecklistSettingsRoute
  '/events/history': typeof EventsHistoryRoute
  '/events/schedule': typeof EventsScheduleRoute
  '/events/series': typeof EventsSeriesRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/inventory/list': typeof InventoryListRoute
  '/inventory/new': typeof InventoryNewRoute
  '/sales/settings': typeof SalesSettingsRoute
  '/sales/stats': typeof SalesStatsRoute
  '/checklist/': typeof ChecklistIndexRoute
  '/costs/': typeof CostsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/costs/products/$id': typeof CostsProductsIdRoute
  '/events/instance/$instanceId': typeof EventsInstanceInstanceIdRoute
  '/inventory/log/batch': typeof InventoryLogBatchRoute
  '/inventory/log/event': typeof InventoryLogEventRoute
  '/inventory/log/restock': typeof InventoryLogRestockRoute
  '/sales/$sessionId/report': typeof SalesSessionIdReportRoute
  '/costs/products/': typeof CostsProductsIndexRoute
  '/sales/$sessionId/': typeof SalesSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/simulate': typeof SimulateRoute
  '/tasks': typeof TasksRoute
  '/checklist/$sessionId': typeof ChecklistSessionIdRoute
  '/checklist/settings': typeof ChecklistSettingsRoute
  '/events/history': typeof EventsHistoryRoute
  '/events/schedule': typeof EventsScheduleRoute
  '/events/series': typeof EventsSeriesRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/inventory/list': typeof InventoryListRoute
  '/inventory/new': typeof InventoryNewRoute
  '/sales/settings': typeof SalesSettingsRoute
  '/sales/stats': typeof SalesStatsRoute
  '/checklist': typeof ChecklistIndexRoute
  '/costs': typeof CostsIndexRoute
  '/events': typeof EventsIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/products': typeof ProductsIndexRoute
  '/sales': typeof SalesIndexRoute
  '/costs/products/$id': typeof CostsProductsIdRoute
  '/events/instance/$instanceId': typeof EventsInstanceInstanceIdRoute
  '/inventory/log/batch': typeof InventoryLogBatchRoute
  '/inventory/log/event': typeof InventoryLogEventRoute
  '/inventory/log/restock': typeof InventoryLogRestockRoute
  '/sales/$sessionId/report': typeof SalesSessionIdReportRoute
  '/costs/products': typeof CostsProductsIndexRoute
  '/sales/$sessionId': typeof SalesSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/simulate': typeof SimulateRoute
  '/tasks': typeof TasksRoute
  '/checklist/$sessionId': typeof ChecklistSessionIdRoute
  '/checklist/settings': typeof ChecklistSettingsRoute
  '/events/history': typeof EventsHistoryRoute
  '/events/schedule': typeof EventsScheduleRoute
  '/events/series': typeof EventsSeriesRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/inventory/list': typeof InventoryListRoute
  '/inventory/new': typeof InventoryNewRoute
  '/sales/settings': typeof SalesSettingsRoute
  '/sales/stats': typeof SalesStatsRoute
  '/checklist/': typeof ChecklistIndexRoute
  '/costs/': typeof CostsIndexRoute
  '/events/': typeof EventsIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/costs/products/$id': typeof CostsProductsIdRoute
  '/events/instance/$instanceId': typeof EventsInstanceInstanceIdRoute
  '/inventory/log/batch': typeof InventoryLogBatchRoute
  '/inventory/log/event': typeof InventoryLogEventRoute
  '/inventory/log/restock': typeof InventoryLogRestockRoute
  '/sales/$sessionId/report': typeof SalesSessionIdReportRoute
  '/costs/products/': typeof CostsProductsIndexRoute
  '/sales/$sessionId/': typeof SalesSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/login'
    | '/meetings'
    | '/settings'
    | '/simulate'
    | '/tasks'
    | '/checklist/$sessionId'
    | '/checklist/settings'
    | '/events/history'
    | '/events/schedule'
    | '/events/series'
    | '/inventory/$itemId'
    | '/inventory/list'
    | '/inventory/new'
    | '/sales/settings'
    | '/sales/stats'
    | '/checklist/'
    | '/costs/'
    | '/events/'
    | '/inventory/'
    | '/products/'
    | '/sales/'
    | '/costs/products/$id'
    | '/events/instance/$instanceId'
    | '/inventory/log/batch'
    | '/inventory/log/event'
    | '/inventory/log/restock'
    | '/sales/$sessionId/report'
    | '/costs/products/'
    | '/sales/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/meetings'
    | '/settings'
    | '/simulate'
    | '/tasks'
    | '/checklist/$sessionId'
    | '/checklist/settings'
    | '/events/history'
    | '/events/schedule'
    | '/events/series'
    | '/inventory/$itemId'
    | '/inventory/list'
    | '/inventory/new'
    | '/sales/settings'
    | '/sales/stats'
    | '/checklist'
    | '/costs'
    | '/events'
    | '/inventory'
    | '/products'
    | '/sales'
    | '/costs/products/$id'
    | '/events/instance/$instanceId'
    | '/inventory/log/batch'
    | '/inventory/log/event'
    | '/inventory/log/restock'
    | '/sales/$sessionId/report'
    | '/costs/products'
    | '/sales/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/login'
    | '/meetings'
    | '/settings'
    | '/simulate'
    | '/tasks'
    | '/checklist/$sessionId'
    | '/checklist/settings'
    | '/events/history'
    | '/events/schedule'
    | '/events/series'
    | '/inventory/$itemId'
    | '/inventory/list'
    | '/inventory/new'
    | '/sales/settings'
    | '/sales/stats'
    | '/checklist/'
    | '/costs/'
    | '/events/'
    | '/inventory/'
    | '/products/'
    | '/sales/'
    | '/costs/products/$id'
    | '/events/instance/$instanceId'
    | '/inventory/log/batch'
    | '/inventory/log/event'
    | '/inventory/log/restock'
    | '/sales/$sessionId/report'
    | '/costs/products/'
    | '/sales/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeetingsRoute: typeof MeetingsRoute
  SettingsRoute: typeof SettingsRoute
  SimulateRoute: typeof SimulateRoute
  TasksRoute: typeof TasksRoute
  ChecklistSessionIdRoute: typeof ChecklistSessionIdRoute
  ChecklistSettingsRoute: typeof ChecklistSettingsRoute
  InventoryItemIdRoute: typeof InventoryItemIdRoute
  InventoryListRoute: typeof InventoryListRoute
  InventoryNewRoute: typeof InventoryNewRoute
  SalesSettingsRoute: typeof SalesSettingsRoute
  SalesStatsRoute: typeof SalesStatsRoute
  ChecklistIndexRoute: typeof ChecklistIndexRoute
  CostsIndexRoute: typeof CostsIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  CostsProductsIdRoute: typeof CostsProductsIdRoute
  InventoryLogBatchRoute: typeof InventoryLogBatchRoute
  InventoryLogEventRoute: typeof InventoryLogEventRoute
  InventoryLogRestockRoute: typeof InventoryLogRestockRoute
  SalesSessionIdReportRoute: typeof SalesSessionIdReportRoute
  CostsProductsIndexRoute: typeof CostsProductsIndexRoute
  SalesSessionIdIndexRoute: typeof SalesSessionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/costs/': {
      id: '/costs/'
      path: '/costs'
      fullPath: '/costs/'
      preLoaderRoute: typeof CostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist/': {
      id: '/checklist/'
      path: '/checklist'
      fullPath: '/checklist/'
      preLoaderRoute: typeof ChecklistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/stats': {
      id: '/sales/stats'
      path: '/sales/stats'
      fullPath: '/sales/stats'
      preLoaderRoute: typeof SalesStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/settings': {
      id: '/sales/settings'
      path: '/sales/settings'
      fullPath: '/sales/settings'
      preLoaderRoute: typeof SalesSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/new': {
      id: '/inventory/new'
      path: '/inventory/new'
      fullPath: '/inventory/new'
      preLoaderRoute: typeof InventoryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/list': {
      id: '/inventory/list'
      path: '/inventory/list'
      fullPath: '/inventory/list'
      preLoaderRoute: typeof InventoryListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$itemId': {
      id: '/inventory/$itemId'
      path: '/inventory/$itemId'
      fullPath: '/inventory/$itemId'
      preLoaderRoute: typeof InventoryItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/series': {
      id: '/events/series'
      path: '/series'
      fullPath: '/events/series'
      preLoaderRoute: typeof EventsSeriesRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/schedule': {
      id: '/events/schedule'
      path: '/schedule'
      fullPath: '/events/schedule'
      preLoaderRoute: typeof EventsScheduleRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/history': {
      id: '/events/history'
      path: '/history'
      fullPath: '/events/history'
      preLoaderRoute: typeof EventsHistoryRouteImport
      parentRoute: typeof EventsRoute
    }
    '/checklist/settings': {
      id: '/checklist/settings'
      path: '/checklist/settings'
      fullPath: '/checklist/settings'
      preLoaderRoute: typeof ChecklistSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist/$sessionId': {
      id: '/checklist/$sessionId'
      path: '/checklist/$sessionId'
      fullPath: '/checklist/$sessionId'
      preLoaderRoute: typeof ChecklistSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/$sessionId/': {
      id: '/sales/$sessionId/'
      path: '/sales/$sessionId'
      fullPath: '/sales/$sessionId/'
      preLoaderRoute: typeof SalesSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costs/products/': {
      id: '/costs/products/'
      path: '/costs/products'
      fullPath: '/costs/products/'
      preLoaderRoute: typeof CostsProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/$sessionId/report': {
      id: '/sales/$sessionId/report'
      path: '/sales/$sessionId/report'
      fullPath: '/sales/$sessionId/report'
      preLoaderRoute: typeof SalesSessionIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/log/restock': {
      id: '/inventory/log/restock'
      path: '/inventory/log/restock'
      fullPath: '/inventory/log/restock'
      preLoaderRoute: typeof InventoryLogRestockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/log/event': {
      id: '/inventory/log/event'
      path: '/inventory/log/event'
      fullPath: '/inventory/log/event'
      preLoaderRoute: typeof InventoryLogEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/log/batch': {
      id: '/inventory/log/batch'
      path: '/inventory/log/batch'
      fullPath: '/inventory/log/batch'
      preLoaderRoute: typeof InventoryLogBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/instance/$instanceId': {
      id: '/events/instance/$instanceId'
      path: '/instance/$instanceId'
      fullPath: '/events/instance/$instanceId'
      preLoaderRoute: typeof EventsInstanceInstanceIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/costs/products/$id': {
      id: '/costs/products/$id'
      path: '/costs/products/$id'
      fullPath: '/costs/products/$id'
      preLoaderRoute: typeof CostsProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsHistoryRoute: typeof EventsHistoryRoute
  EventsScheduleRoute: typeof EventsScheduleRoute
  EventsSeriesRoute: typeof EventsSeriesRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsInstanceInstanceIdRoute: typeof EventsInstanceInstanceIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsHistoryRoute: EventsHistoryRoute,
  EventsScheduleRoute: EventsScheduleRoute,
  EventsSeriesRoute: EventsSeriesRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsInstanceInstanceIdRoute: EventsInstanceInstanceIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  MeetingsRoute: MeetingsRoute,
  SettingsRoute: SettingsRoute,
  SimulateRoute: SimulateRoute,
  TasksRoute: TasksRoute,
  ChecklistSessionIdRoute: ChecklistSessionIdRoute,
  ChecklistSettingsRoute: ChecklistSettingsRoute,
  InventoryItemIdRoute: InventoryItemIdRoute,
  InventoryListRoute: InventoryListRoute,
  InventoryNewRoute: InventoryNewRoute,
  SalesSettingsRoute: SalesSettingsRoute,
  SalesStatsRoute: SalesStatsRoute,
  ChecklistIndexRoute: ChecklistIndexRoute,
  CostsIndexRoute: CostsIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  CostsProductsIdRoute: CostsProductsIdRoute,
  InventoryLogBatchRoute: InventoryLogBatchRoute,
  InventoryLogEventRoute: InventoryLogEventRoute,
  InventoryLogRestockRoute: InventoryLogRestockRoute,
  SalesSessionIdReportRoute: SalesSessionIdReportRoute,
  CostsProductsIndexRoute: CostsProductsIndexRoute,
  SalesSessionIdIndexRoute: SalesSessionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
